/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

/**
 *
 * @author ALUNO
 */
public class TelaPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadastrarCliente = new javax.swing.JMenuItem();
        jMenuItemCadastrarVaga = new javax.swing.JMenuItem();
        jMenuPesquisa = new javax.swing.JMenu();
        jMenuItemPesquisarCliente = new javax.swing.JMenuItem();
        jMenuItemPesquisarVaga = new javax.swing.JMenuItem();
        jMenuItemPesquisarLocacao = new javax.swing.JMenuItem();
        jMenuLocacao = new javax.swing.JMenu();
        jMenuItemEfetuarLocacao = new javax.swing.JMenuItem();
        jMenuItemFinalizarLocacao = new javax.swing.JMenuItem();

        setMinimumSize(new java.awt.Dimension(800, 600));

        jInternalFrame1.setVisible(true);

        jMenuCadastro.setText("Cadastro");

        jMenuItemCadastrarCliente.setText("Cadastrar Cliente");
        jMenuCadastro.add(jMenuItemCadastrarCliente);

        jMenuItemCadastrarVaga.setText("Cadastrar Vaga");
        jMenuCadastro.add(jMenuItemCadastrarVaga);

        jMenuBar1.add(jMenuCadastro);

        jMenuPesquisa.setText("Pesquisa");

        jMenuItemPesquisarCliente.setText("Pesquisar Cliente");
        jMenuPesquisa.add(jMenuItemPesquisarCliente);

        jMenuItemPesquisarVaga.setText("Pesquisar Vaga");
        jMenuPesquisa.add(jMenuItemPesquisarVaga);

        jMenuItemPesquisarLocacao.setText("Pesquisar Locação");
        jMenuPesquisa.add(jMenuItemPesquisarLocacao);

        jMenuBar1.add(jMenuPesquisa);

        jMenuLocacao.setText("Locação");

        jMenuItemEfetuarLocacao.setText("Efetuar Locação");
        jMenuLocacao.add(jMenuItemEfetuarLocacao);

        jMenuItemFinalizarLocacao.setText("Finalizar Locação");
        jMenuLocacao.add(jMenuItemFinalizarLocacao);

        jMenuBar1.add(jMenuLocacao);

        jInternalFrame1.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 529, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItemCadastrarCliente;
    private javax.swing.JMenuItem jMenuItemCadastrarVaga;
    private javax.swing.JMenuItem jMenuItemEfetuarLocacao;
    private javax.swing.JMenuItem jMenuItemFinalizarLocacao;
    private javax.swing.JMenuItem jMenuItemPesquisarCliente;
    private javax.swing.JMenuItem jMenuItemPesquisarLocacao;
    private javax.swing.JMenuItem jMenuItemPesquisarVaga;
    private javax.swing.JMenu jMenuLocacao;
    private javax.swing.JMenu jMenuPesquisa;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
